export const plans = [
  {
    name: 'Royal',
    title: '$20.000 COP/mes',
    price: '20000',
    description: 'Ideal para emprendedores individuales.',
    features: [
      'Asesoría por chat, email y WhatsApp.',
      'Hosting y SSL gratuitos.',
      'Venta en múltiples idiomas y moneda local.',
      'Panel de estadísticas básicas.',
      'Seguimiento de productos para vendedores y compradores.',
      'Optimización de precios con IA (básico).',
      'Hasta 5 plantillas para personalizar la tienda.',
    ],
    buttonText: 'Suscribirse ahora',
    className: 'bg-white',
  },
  {
    name: 'Majestic',
    title: '$30.000 COP/mes',
    price: '30000',
    description: 'Para equipos pequeños que quieren crecer.',
    features: [
      'Todo en Royal.',
      'Panel de estadísticas avanzadas.',
      'Gestión de múltiples vendedores.',
      'Automatización de respuestas a clientes.',
      'Personalización avanzada con Strapi.',
      'Soporte prioritario 24/7.',
      'Integraciones con redes sociales.',
    ],
    buttonText: 'Suscribirse ahora',
    className: 'bg-white',
    popular: true,
  },
  {
    name: 'Imperial',
    title: '$45.000 COP/mes',
    price: '45000',
    description: 'Para negocios en expansión con alto tráfico.',
    features: [
      'Todo en Majestic.',
      'Membresías y descuentos exclusivos para clientes.',
      'Almacenamiento y carga de productos sin límite.',
      'Gestión avanzada de pedidos y envíos.',
      'Marca blanca para personalización total.',
      'API para conectar con otros servicios.',
      'Analítica y reportes personalizados.',
      'Atención VIP con gestor de cuenta dedicado.',
    ],
    buttonText: 'Suscribirse ahora',
    className: 'bg-white',
  },
]
