import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ConfigureAmplifyClientSide from "@/components/config-ssr/ConfigureAmplify";
import "@aws-amplify/ui-react/styles.css";
import "./global.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Fasttify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <>
          <ConfigureAmplifyClientSide />
          {children}
        </>
      </body>
    </html>
  );
}
