import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ConfigureAmplifyClientSide from '@/utils/ConfigureAmplify'
import './global.css'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Fasttify',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/fast@4x.webp',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigureAmplifyClientSide />

        {children}
      </body>
    </html>
  )
}
